server:
  port: 10000
spring:
  application:
    name: emporium-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
  server:
    eviction-interval-timer-in-ms: 10000 #剔除已经宕机的服务
    eviction-self-preservation: false #关闭自我保护