server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.1.105
    username: zacks
    password: 123456
    virtual-host: /emp
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
  #  instance-id: ${spring.application.name}.${server.port}