server:
  port: 8087
spring:
  application:
    name: auth-service
ep:
  jwt:
    secret: emporium@Login(Auth}*^31)emp% # 登录校验的密钥
    pubKeyPath: E:\\temp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: E:\\temp\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: EMP_TOKEN
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
    registry-fetch-interval-seconds: 10 #拉取服务时间
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1


